### ISSUE TITLE
Implement Author Class

### ISSUE THREAD

**Issue by RyanGuinchard** [RyanGuinchard/Sem3MidtermSprint#2]
`Author`: A class that represents an author. The `Author` class should have properties 
such as name, data of birth and a list of books they have written.

**Comment by ks-chris352010** [comment]
Mission accomplished, SIR!

**Comment by ks-chris352010** [comment]
Mission accomplished, SIR!

**Comment by ks-chris352010** [comment]
Mission accomplished, SIR!
